### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by emmanuelog40** [Cvolton/GMDprivateServer#235] opened 2018-04-06 18:16 UTC
The database doesnt work it says about create table 'accomments'

**Comment by Jecket22** [comment] 2018-04-06 18:33
Try to re-download the files or download a newer version of database.sql. If this shouldn't fix, rename with notepad in the file "accomments" into "acccomments"

**Comment by emmanuelog40** [comment] 2018-04-06 19:53
Jecket22 add me on discord 
emmanuelog40#3798
Try to contact me to help me
In more stuff :>

**Comment by emmanuelog40** [comment] 2018-04-06 20:32
It still doesnt work
:(

**Comment by emmanuelog40** [comment] 2018-04-06 22:15
Omfg

**Comment by emmanuelog40** [comment] 2018-04-06 22:16
Help
Jesus

**Comment by emmanuelog40** [comment] 2018-04-06 22:17
Help
Jesus

**Comment by Cvolton** [comment] 2018-05-01 17:02
duplicate of #237 (actually it's the opposite, but people have been posting solutions there instead)

**Closed by Cvolton** 2018-05-01 17:02 UTC
