### ISSUE TITLE
phpMyAdmin Bug

### ISSUE THREAD

**Issue by AnimeDasher** [Cvolton/GMDprivateServer#564] opened 2020-03-28 10:25 UTC
Whenever I try and login to phpMyAdmin i get this error:
mysqli_real_connect(): (HY000/1040): Too many connections
I have no idea on how to fix this and there does not seem to be anything online.

**Comment by AnimeDasher** [comment] 2020-03-28 10:37
7m.pl is down i think

**Comment by RealistikDash** [comment] 2020-03-29 17:41
That is a 7m/phpmyadmin issue. Not with this code. GitHub issues are reserved for issues with the project itself.

**Comment by EMREOYUN** [comment] 2020-03-30 06:55
7m.pl issue. Please close this issue. It is not caused by our code.

**Closed** 2020-03-30 22:26 UTC
