### ISSUE TITLE
Some error thingy (Happening in a lot of the files)

### ISSUE THREAD

**Issue by TheOpGaming** [Cvolton/GMDprivateServer#83] opened 2017-05-18 22:22 UTC
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db677710812.links' doesn't exist' in /homepages/2/d677650796/htdocs/gdp/tools/levelReupload.php:111 Stack trace: #0 /homepages/2/d677650796/htdocs/gdp/tools/levelReupload.php(111): PDOStatement->execute(Array) #1 {main} thrown in /homepages/2/d677650796/htdocs/gdp/tools/levelReupload.php on line 111

^^^^^^^^^^^^^^^^^^^
Not using altervista

**Comment by TheOpGaming** [comment] 2017-05-18 22:24
could it be something to do with MySQL 5.5?

**Comment by TheOpGaming** [comment] 2017-05-18 22:41
Level download failed also

**Comment by AggPro** [comment] 2017-05-31 16:08
whats your php version?

**Comment by Cvolton** [comment] 2017-06-01 06:18
This is caused by the database structure not matching the version of the files, this is usually caused by updating improperly

**Comment by TheOpGaming** [comment] 2017-06-23 12:31
ok

**Comment by TheOpGaming** [comment] 2017-06-24 12:01
is there a way to fix it? php 5.6 btw...

**Comment by TheOpGaming** [comment] 2017-07-10 15:36
still happening... Dunno what to do..

**Comment by AggPro** [comment] 2017-07-21 17:07
try using newer php xd

**Comment by pavlukivan** [comment] 2018-01-09 12:54
again, import the db structure
@Cvolton suggestion: auto table import script, opened #164

**Comment by EndNation** [comment] 2018-03-31 05:54
@TheOpGaming Easy, you goto the line it says where there is an error then search on google how to fix the error, I fixed some alr

**Comment by geniiii** [comment] 2019-04-23 23:53
your gdps has hiv

**Comment by Cvolton** [comment] 2020-10-23 16:02
no constructive response in over 3 years, closing

**Closed by Cvolton** 2020-10-23 16:02 UTC
