### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by hiimjustin000** [Cvolton/GMDprivateServer#573] opened 2020-04-05 22:48 UTC
I edited the base64 encoded strings and the plaintext strings, I uploaded the files and the database, I edited connection.php, and I still get an error when registering an account. "Something went wrong".

I went to `http://thequadgdps.7m.pl/database/accounts/registerGJAccount.php` on my web browser, and I am hit with a 503. Why is the 503 there? It's not there on the other GDPSes I made.

**Comment by EMREOYUN** [comment] 2020-04-06 06:34
Which hosting you use?

**Comment by EMREOYUN** [comment] 2020-04-06 06:37
Contact with 7m.pl. It seems server sided error.

**Comment by Cvolton** [comment] 2020-04-06 16:41
you most likely edited connection.php wrong, $servername must be the hostname of the mysql server

**Comment by EMREOYUN** [comment] 2020-04-06 16:58
> you most likely edited connection.php wrong, $servername must be the hostname of the mysql server

I think it is not force a 503 error.

**Comment by Cvolton** [comment] 2020-04-06 17:11
> I think it is not force a 503 error.

the 503 error happens because the server times out while running the php script, this is usually caused by the web server not being able to connect to the mysql server

**Comment by hiimjustin000** [comment] 2020-04-06 17:54
Lemme show you connection.php
```php
<?php
$servername = "sql1.7m.pl";
$username = "db-user31194";
$password = "censored";
$dbname = "db-user31194";
?>
```

**Comment by EMREOYUN** [comment] 2020-04-06 18:12
> > I think it is not force a 503 error.
> 
> the 503 error happens because the server times out while running the php script, this is usually caused by the web server not being able to connect to the mysql server

Weird, mine website goes 500 when fails to connect database.

**Comment by Cvolton** [comment] 2020-04-06 18:25
> Lemme show you connection.php
> 
> ```
> <?php
> $servername = "sql1.7m.pl";
> $username = "db-user31194";
> $password = "censored";
> $dbname = "db-user31194";
> ?>
> ```

this seems correct, you can try sql1.7m.pl with localhost

**Comment by Cvolton** [comment] 2020-04-06 18:26
> > > I think it is not force a 503 error.
> > 
> > 
> > the 503 error happens because the server times out while running the php script, this is usually caused by the web server not being able to connect to the mysql server
> 
> Weird, mine website goes 500 when fails to connect database.

it depends on the server configuration, 7m.pl is behind a reverse proxy, which times out in a shorther amount of time than the actual php script

**Comment by DarkGD123** [comment] 2020-04-08 05:22
> Lemme show you connection.php
> 
> ```
> <?php
> $servername = "sql1.7m.pl";
> $username = "db-user31194";
> $password = "censored";
> $dbname = "db-user31194";
> ?>
> ```

It should be `sql.7m.pl` not `sql1.7m.pl`

**Comment by hiimjustin000** [comment] 2020-04-08 19:51
But... they changed it to sql1...

**Comment by DarkGD123** [comment] 2020-04-09 02:38
It doesn't work @hiimjustin000 it's just the website name changed

**Comment by EMREOYUN** [comment] 2020-04-09 06:02
That's why i always hate free hostings.

**Comment by DarkGD123** [comment] 2020-04-13 12:30
lol same

**Comment by Cvolton** [comment] 2020-04-13 21:08
> > Lemme show you connection.php
> > ```
> > <?php
> > $servername = "sql1.7m.pl";
> > $username = "db-user31194";
> > $password = "censored";
> > $dbname = "db-user31194";
> > ?>
> > ```
> 
> this seems correct, you can try sql1.7m.pl with localhost

you can try **replacing** sql1.7m.pl with localhost

just noticed I missed a word there

**Comment by EMREOYUN** [comment] 2020-04-14 06:44
@cvolton LMAO

**Comment by Phytee** [comment] 2020-04-15 09:52
Mine worked when i replaced sql1.7m.pl with sql.7m.pl

**Comment by DarkGD123** [comment] 2020-04-15 11:40
Use `sql.7m.pl` also when close issue

**Comment by Phytee** [comment] 2020-04-17 17:11
@Cvolton close this

**Comment by QuantumWormhole** [comment] 2020-06-07 06:11
Are you using FileZilla?

**Comment by fancythedeveloper** [comment] 2020-06-07 14:15
Stop assuming that's the issue.

**Comment by EMREOYUN** [comment] 2020-06-07 16:41
> Stop assuming that's the issue.

It is RESOLVED and must be closed if unnecessary.

**Comment by QuantumWormhole** [comment] 2020-06-07 20:42
k

**Comment by HGStyle** [comment] 2024-05-20 17:06
issue resolved 4 years ago but its still not closed lol

**Closed** 2024-05-20 17:38 UTC
