### ISSUE TITLE
This happens when i try to change the password

### ISSUE THREAD

**Issue by UpriseDragon** [Cvolton/GMDprivateServer#221] opened 2018-03-22 11:48 UTC
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'salt' cannot be null' in /membri/gmdragon5/database/tools/account/changePassword.php:43 Stack trace: #0 /membri/gmdragon5/database/tools/account/changePassword.php(43): PDOStatement->execute(Array) #1 {main} thrown in /membri/gmdragon5/database/tools/account/changePassword.php on line 43

**Comment by EndNation** [comment] 2018-03-30 12:44
How did u try to change the password??? I made a .php that allows u to change password easily

**Comment by UpriseDragon** [comment] 2018-03-31 13:13
The gdps password i mean

**Comment by Cvolton** [comment] 2018-04-02 10:25
duplicate of #148

**Closed by Cvolton** 2018-04-02 10:25 UTC
