### ISSUE TITLE
Level Completion Kick

### ISSUE THREAD

**Issue by fancythedeveloper** [Cvolton/GMDprivateServer#557] opened 2020-03-23 22:15 UTC
Anyway to fix getting kicked out of a level on a GDPS right before hitting the finish glow at the end of a level? The first level I uploaded worked mine but the two others don't.

**Comment by Cvolton** [comment] 2020-03-24 02:21
dupe of
#537 #437 #296 #284 #212 #191 #129 and possibly more
tl;dr levels above 2* must be at least medium length

**Closed by Cvolton** 2020-03-24 02:21 UTC

**Comment by fancythedeveloper** [comment] 2020-03-24 18:12
k
